basePath: /
definitions:
  domain.User:
    properties:
      login:
        type: string
      password:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: Crime app auth provides authentication for crime-app microservices.
  title: Crime app auth
  version: "1.0"
paths:
  /users/login:
    post:
      consumes:
      - application/json
      description: authorize user in crime-app microservices ecosystem
      parameters:
      - description: User's consisted of login and password
        in: body
        name: id
        required: true
        schema:
          $ref: '#/definitions/domain.User'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            type: string
      summary: provides signing in operation
      tags:
      - users
  /users/register:
    post:
      consumes:
      - application/json
      description: registers user in crime-app microservices ecosystem
      parameters:
      - description: User's consisted of login and password
        in: body
        name: id
        required: true
        schema:
          $ref: '#/definitions/domain.User'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/domain.User'
      summary: provides signing up operation
      tags:
      - users
swagger: "2.0"
